[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.build]
cmds = [
  'cd backend',
  'dotnet restore',
  'dotnet publish -c Release -o out'
]

[phases.start]
cmd = 'cd backend/out && dotnet FlexCard.API.dll'

[variables]
PORT = '8080'